name: Handle Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Handle Issue Comment
      if: github.event.comment.body == 'I want it now'
      uses: estrada9166/issue-assigner@v1
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        WITH_COMMENTS: true
