name: Handle Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Handle Issue Comment
      run: |
        if: github.event.comment.body == 'I want it now'
        echo I will assign the commenting user
